[agent]
  interval = "10s"
  round_interval = true
  flush_interval = "10s"
  omit_hostname = true
  debug = true

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]
  topics = ["application/+/device/+/event/up"]
  qos = 0
  connection_timeout = "30s"
  client_id = "telegraf_chirpstack"
  persistent_session = true

  data_format = "json_v2"

  [[inputs.mqtt_consumer.json_v2]]
    measurement_name = "lorawan_uplink"

    # Tags
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "deviceInfo.devEui"
      rename = "dev_eui"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "deviceInfo.deviceName"
      rename = "device"

    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "deviceInfo.applicationName"
      rename = "app"

    # Champs radio (optionnels)
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "fCnt"
      rename = "fcnt"
      type = "int"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "rxInfo.0.rssi"
      rename = "rssi"
      type = "int"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "rxInfo.0.snr"
      rename = "snr"
      type = "float"

    # Mesures décodées (à adapter si tes clés diffèrent)
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "object.temperature_c"
      rename = "temperature_c"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "object.humidity_pct"
      rename = "humidity_pct"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "object.pressure_hpa"
      rename = "pressure_hpa"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "object.digital_input"
      rename = "digital_input"
      type = "float"

    # Header (si tu veux les garder)
    [[inputs.mqtt_consumer.json_v2.field]]
      path = "object.header_version"
      rename = "header_version"
      type = "float"

    [[inputs.mqtt_consumer.json_v2.field]]
      path = "object.header_msg_type"
      rename = "header_msg_type"
      type = "float"

    # header_device est une string => mieux en TAG
    [[inputs.mqtt_consumer.json_v2.tag]]
      path = "object.header_device"
      rename = "header_device"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb:8086"]
  token = "$INFLUX_TOKEN"
  organization = "alora"
  bucket = "chirpstack"