apiVersion: 1

datasources:
  - name: InfluxDB (ChirpStack)
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: alora
      defaultBucket: chirpstack
    secureJsonData:
      token: change-me-super-token